# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/choose_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1650, 950)
        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(0, 0, 1651, 951))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("assets\\background.png"))
        self.background.setObjectName("background")
        self.logo = QtWidgets.QLabel(Form)
        self.logo.setGeometry(QtCore.QRect(430, 90, 790, 360))
        self.logo.setStyleSheet("")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("assets\\logo.png"))
        self.logo.setObjectName("logo")
        self.backstage_frame = QtWidgets.QFrame(Form)
        self.backstage_frame.setGeometry(QtCore.QRect(500, 500, 320, 330))
        self.backstage_frame.setStyleSheet("#backstage_frame {\n"
"    background-color: #EEEEEE;\n"
"    border: 2px solid black;\n"
"    border-radius: 15px;\n"
"}")
        self.backstage_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.backstage_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.backstage_frame.setObjectName("backstage_frame")
        self.identity_frame_title = QtWidgets.QLabel(self.backstage_frame)
        self.identity_frame_title.setGeometry(QtCore.QRect(0, 0, 320, 60))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.identity_frame_title.setFont(font)
        self.identity_frame_title.setStyleSheet("background-color: #D0D0D0;\n"
"border: 2px solid black;\n"
"border-top-left-radius: 15px;\n"
"border-top-right-radius: 15px;\n"
"")
        self.identity_frame_title.setTextFormat(QtCore.Qt.PlainText)
        self.identity_frame_title.setAlignment(QtCore.Qt.AlignCenter)
        self.identity_frame_title.setObjectName("identity_frame_title")
        self.name_frame = QtWidgets.QFrame(self.backstage_frame)
        self.name_frame.setGeometry(QtCore.QRect(20, 80, 280, 70))
        self.name_frame.setStyleSheet("")
        self.name_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.name_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.name_frame.setObjectName("name_frame")
        self.name_title = QtWidgets.QLabel(self.name_frame)
        self.name_title.setGeometry(QtCore.QRect(100, 0, 80, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.name_title.setFont(font)
        self.name_title.setAlignment(QtCore.Qt.AlignCenter)
        self.name_title.setObjectName("name_title")
        self.frame = QtWidgets.QFrame(self.name_frame)
        self.frame.setGeometry(QtCore.QRect(0, 40, 280, 30))
        self.frame.setStyleSheet("background-color: white;\n"
"border: 2px solid gray;\n"
"border-radius: 15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(240, 5, 21, 21))
        self.label.setStyleSheet("background-color: white;\n"
"border:0;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("assets\\arrow.png"))
        self.label.setObjectName("label")
        self.name_frame_2 = QtWidgets.QFrame(self.backstage_frame)
        self.name_frame_2.setGeometry(QtCore.QRect(20, 170, 280, 70))
        self.name_frame_2.setStyleSheet("")
        self.name_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.name_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.name_frame_2.setObjectName("name_frame_2")
        self.name_title_2 = QtWidgets.QLabel(self.name_frame_2)
        self.name_title_2.setGeometry(QtCore.QRect(100, 0, 80, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.name_title_2.setFont(font)
        self.name_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.name_title_2.setObjectName("name_title_2")
        self.frame_2 = QtWidgets.QFrame(self.name_frame_2)
        self.frame_2.setGeometry(QtCore.QRect(0, 40, 280, 30))
        self.frame_2.setStyleSheet("background-color: white;\n"
"border: 2px solid gray;\n"
"border-radius: 15px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(240, 5, 21, 21))
        self.label_2.setStyleSheet("background-color: white;\n"
"border:0;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("assets\\arrow.png"))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.backstage_frame)
        self.pushButton.setGeometry(QtCore.QRect(115, 265, 90, 35))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:#D0D0D0;\n"
"border: 2px solid gray;\n"
"border-radius: 15px;")
        self.pushButton.setObjectName("pushButton")
        self.monitor_frame = QtWidgets.QFrame(Form)
        self.monitor_frame.setGeometry(QtCore.QRect(840, 500, 320, 240))
        self.monitor_frame.setStyleSheet("#monitor_frame {\n"
"    background-color: #EEEEEE;\n"
"    border: 2px solid black;\n"
"    border-radius: 15px;\n"
"}")
        self.monitor_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.monitor_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.monitor_frame.setObjectName("monitor_frame")
        self.identity_frame_title_2 = QtWidgets.QLabel(self.monitor_frame)
        self.identity_frame_title_2.setGeometry(QtCore.QRect(0, 0, 320, 61))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.identity_frame_title_2.setFont(font)
        self.identity_frame_title_2.setStyleSheet("background-color: #D0D0D0;\n"
"border: 2px solid black;\n"
"border-top-left-radius: 15px;\n"
"border-top-right-radius: 15px;\n"
"")
        self.identity_frame_title_2.setTextFormat(QtCore.Qt.PlainText)
        self.identity_frame_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.identity_frame_title_2.setObjectName("identity_frame_title_2")
        self.name_frame_3 = QtWidgets.QFrame(self.monitor_frame)
        self.name_frame_3.setGeometry(QtCore.QRect(20, 80, 280, 70))
        self.name_frame_3.setStyleSheet("")
        self.name_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.name_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.name_frame_3.setObjectName("name_frame_3")
        self.name_title_3 = QtWidgets.QLabel(self.name_frame_3)
        self.name_title_3.setGeometry(QtCore.QRect(100, 0, 80, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.name_title_3.setFont(font)
        self.name_title_3.setAlignment(QtCore.Qt.AlignCenter)
        self.name_title_3.setObjectName("name_title_3")
        self.frame_3 = QtWidgets.QFrame(self.name_frame_3)
        self.frame_3.setGeometry(QtCore.QRect(0, 40, 280, 30))
        self.frame_3.setStyleSheet("background-color: white;\n"
"border: 2px solid gray;\n"
"border-radius: 15px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(240, 5, 21, 21))
        self.label_3.setStyleSheet("background-color: white;\n"
"border:0;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("assets\\arrow.png"))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.monitor_frame)
        self.pushButton_2.setGeometry(QtCore.QRect(115, 175, 90, 35))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color:#D0D0D0;\n"
"border: 2px solid gray;\n"
"border-radius: 15px;")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.identity_frame_title.setText(_translate("Form", "監控視窗"))
        self.name_title.setText(_translate("Form", "選擇場所"))
        self.name_title_2.setText(_translate("Form", "選擇相機"))
        self.pushButton.setText(_translate("Form", "確認"))
        self.identity_frame_title_2.setText(_translate("Form", "流量管理"))
        self.name_title_3.setText(_translate("Form", "選擇場所"))
        self.pushButton_2.setText(_translate("Form", "確認"))
